name: js_util
description: Utilities to access JavaScript from Dart.
version: 0.2.0
author: Fluidic Team <dev@fluidic.io>
homepage: https://github.com/fluidic/js_util

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  js: '>=0.6.0 <0.7.0'
  quiver_iterables: '>=1.0.0 <2.0.0'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  test: '>=0.12.0 <0.13.0'
